### ISSUE TITLE
[Error] Heartbeat thread failed due to unexpected error

### ISSUE THREAD

**Issue by hooniegit** [hooniegit/ConsumerPackage#1]
### 개요
Consumer 어플리케이션이 차지하는 Java Heap Space가 지속적으로 증가하여 리소스 한계를 초과하는 문제 발생 <br>

### Error Code
``` bash
2024-07-11 12:16:29,131 [1;31mdisableAnsi=false[m-  red [35m${sys:PID}[m [ad | DemoGroup7] [36m.c.i.AbstractCoordinator$HeartbeatThread[m : [Consumer clientId=consumer-DemoGroup7-2, groupId=DemoGroup7] Heartbeat thread failed due to unexpected error

java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:64)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:363)
	at org.apache.kafka.common.memory.MemoryPool$1.tryAllocate(MemoryPool.java:30)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:102)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:585)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:281)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:322)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1490)

2024-07-11 12:16:29,223 [32mdisableAnsi=false[m-green [35m${sys:PID}[m [pool-2-thread-2] [36mk.c.c.i.ConsumerRebalanceListenerInvoker[m : [Consumer clientId=consumer-DemoGroup7-2, groupId=DemoGroup7] Revoke previously assigned partitions DemoTopic7-1
Received, Partition: 4, Offset: 751, by ThreadID: 114
2024-07-11 12:16:29.298 [32m-green [35m${sys:PID}[m [pool-7-thread-6] [36mc.h.L.TaskEventHandler                  [m : Spent Time : 0 ms
[m2024-07-11 12:16:29,394 [1;31mdisableAnsi=false[m-  red [35m${sys:PID}[m [ad | DemoGroup7] [36m.c.i.AbstractCoordinator$HeartbeatThread[m : [Consumer clientId=consumer-DemoGroup7-5, groupId=DemoGroup7] Heartbeat thread failed due to unexpected error

java.lang.OutOfMemoryError: Java heap space
```

**Comment by hooniegit** [comment]
# Trial 1
### 메모리 사용량 보고서 확인
![스크린샷 2024-07-11 153859](https://github.com/hooniegit/ConsumerPackage/assets/130134750/2033fd81-6d3c-47df-9c94-249ebe24b75c)
<br>
- 데이터 처리 로직을 포함하는 LMAX RingBuffer 및 TaskEvent에서 메모리 누수
- 도합 1.9GB의 힙 메모리 사용
<br>

### 힙 메모리 수치 증가 시도 (2배)
: 4GB까지 가비지가 쌓이는지의 여부 확인
``` bash
java -Xms1024m -Xmx4096m
```

**Comment by hooniegit** [comment]
# Trial 2
### Garbage Collection 사용 (GC1)
``` bash
-Xms1024m -Xmx4096m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=C:\Users\dhkim\git\ConsumerPackage\dump\dump.hprof
```

**Comment by hooniegit** [comment]
# Trial 3
### 로직 수정
1. Poll 작업을 통해 생성한 ConsumerRecords를 Thread 종료 시점에 초기화
``` java
			while (running.get()) {
				// poll 작업을 수행하고, 반환값을 기반으로 ConsumerRecords 객체로 구성합니다.
				// ** 데이터 형식자<Key, Message>는 기업 표준으로 수정되어야 합니다 **
				ConsumerRecords<String, String> records = consumer.poll(Duration.ofMillis(100));
				
				// 수신 데이터를 기반으로 한 작업 스레드를 시작합니다.
				// ** 데이터 형식자<Key, Message>는 기업 표준으로 수정되어야 합니다 **
				for (ConsumerRecord<String, String> record : records) {
					
					// 링 버퍼를 통해 이벤트 핸들러에 이벤트를 전달합니다.
					ringBuffer.publishEvent((event, sequence) -> event.setRecord(record));

					// 수동 오프셋 커밋을 위해 오프셋 정보를 갱신합니다.
					currentOffsets.put(
							new TopicPartition(record.topic(), record.partition()), 
							new OffsetAndMetadata(record.offset()+1, null));
					
				} 
				
				// 객체를 초기화하고 수동으로 오프셋을 커밋합니다.
				records = null;
				consumer.commitAsync(currentOffsets, null);
			}
```
<br>
2. 이벤트 처리 작업 종료 시 TaskEvent 객체 초기화
``` java
        measureExecutionTime(() -> {
            ConsumerRecord<String, String> record = event.getRecord();
//            
//            // TEST: 콘솔에 수신 데이터를 출력합니다.
            Date date = new Date(record.timestamp());
            System.out.println("Received, Partition: "
                    + record.partition() + ", Offset: " + record.offset() + 
                    ", timestamp: " + sdf.format(date) +
                    ", by ThreadID: " + Thread.currentThread().getId());
            
            // 완료된 이벤트 객체를 초기화합니다.
        	event.clear();
        });
```
<br>

# 결과
![스크린샷 2024-07-12 082505](https://github.com/user-attachments/assets/cd79b809-6539-4cdc-91ba-09c7d7f229dc)
- 점유율이 더 이상 늘어나지 않고 850MB에서 유지되는 것을 확인
- 보다 장기적인 테스트를 통한 안정성 검토가 필요

**Comment by hooniegit** [comment]
> 장기적으로 생성되는 Garbage Memory에 대한 대응 필요
- 어플리케이션 생명주기 고려
- 재사용성이 높은 리소스 정리
- `System.gc()` 직접 호출
